#Same as execute_script, but experimenting on a small dataset.
#!/bin/bash

#PROJ_DIR is where all the temporary files are stored.
#PROJ_DIR is structured as follows:
#__DIR/
#_____gmm_list.npz (GMMs generated by gmm.py)
#_____FISHERS(.fisher files)
#_____TMP_FEATURES/ (stores intermediate .feature files)

#Python source code directory
SRC="/afs/cs.stanford.edu/u/anenberg/code/snrThesis/src/"
PROJ_DIR="/afs/cs.stanford.edu/u/anenberg/scr/snrThesis/Jan_30"
vs_PROJ_DIR="/afs/cs.stanford.edu/u/anenberg/scr/snrThesis/BATCH_EXP"



#The video data can come from a number of different directories.
UCF_DIR="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Training/videos/"
VALID_DIR="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Validation/videos/"
BACK_DIR="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Background/videos/"
TEST_DIR="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Test/videos/"

#Full data sets
UCF_FULL="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Training/train_set.txt"
VALID_FULL="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Validation/validation_primaryclass.txt"
BACK_FULL=""
TEST_FULL="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Test/test_primaryclass.txt"



UCF_vs_list=$vs_PROJ_DIR"/ucf_vs.txt"

#Generate the gmm_list.npz file.
#python $SRC"consolidateFiles.py" $UCF_DIR -l $UCF_FULL | python $SRC"gmm.py" 120 $PROJ_DIR -s 0.005

#python $SRC"consolidateFiles.py" $UCF_DIR -l $UCF_FULL \
#| python $SRC"computeFVs.py" $PROJ_DIR -t 5


#Build the class index
CLASS_INDEX="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Training/ucfTrainTestlist/classInd.txt"
CLASS_INDEX_OUT=$SRC"class_index"
#python compute_UCF101_class_index.py $CLASS_INDEX $CLASS_INDEX_OUT
CLASS_INDEX_FILE=$CLASS_INDEX_OUT".npz"


#The training and testing cuts.
UCF_train1="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Training/ucfTrainTestlist/trainlist01.txt"
UCF_test1="/afs/cs.stanford.edu/group/cvgl/rawdata/THUMOS2014/Training/ucfTrainTestlist/testlist01.txt"



python $SRC"classify_experiment.py" $PROJ_DIR $UCF_train1 $UCF_test1 $CLASS_INDEX_FILE






